### ISSUE TITLE
Receiving 304 error upon downloading tarball

### ISSUE THREAD

**Issue by emacgillavry** [sabas/genfontgl#6]
runnning npm install, I hit the following error:

> Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.8/node-v47-linux-x64.tar.gz

**Comment by sabas** [comment]
Seems more of an upstream problem... 
https://github.com/mapbox/node-fontnik/issues/130

**Comment by emacgillavry** [comment]
Thnx for looking into this! Working my way through dependencies :-)

Op 4 feb. 2017 17:05 schreef "Stefano" <notifications@github.com>:

**Comment by emacgillavry** [comment]
Upgraded to node 6 and works now. Thanks!
